export const KEYBOARD = {
    Backspace: "Backspace",
    Space: " ",
    Enter: "Enter",
    Shift: "Shift",
    Control: "Control",
    Alt: "Alt",
    Tab: "Tab",
    CapsLock: "CapsLock",
    Escape: "Escape",
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    Number0: "0",
    Number1: "1",
    Number2: "2",
    Number3: "3",
    Number4: "4",
    Number5: "5",
    Number6: "6",
    Number7: "7",
    Number8: "8",
    Number9: "9",
    Q: "q",
    W: "w",
    E: "e",
    R: "r",
    T: "t",
    Y: "y",
    U: "u",
    I: "i",
    O: "o",
    P: "p",
    A: "a",
    S: "s",
    D: "d",
    F: "f",
    G: "g",
    H: "h",
    J: "j",
    K: "k",
    L: "l",
    M: "m",
    N: "n",
    B: "b",
    C: "c",
    V: "v",
    X: "x",
    Z: "z",
    Comma: ",",
    Period: ".",
    Semicolon: ";",
    Quote: "'",
    BracketLeft: "[",
    BracketRight: "]",
    Backslash: "\\",
    Slash: "/",
    Minus: "-",
    Equal: "=",
    Backquote: "`",
    
}

export const KEYBOARD_TEXT_KEYS = [
    KEYBOARD.Shift,
    KEYBOARD.Number0,
    KEYBOARD.Number1,
    KEYBOARD.Number2,
    KEYBOARD.Number3,
    KEYBOARD.Number4,
    KEYBOARD.Number5,
    KEYBOARD.Number6,
    KEYBOARD.Number7,
    KEYBOARD.Number8,
    KEYBOARD.Number9,
    KEYBOARD.Q,
    KEYBOARD.W,
    KEYBOARD.E,
    KEYBOARD.R,
    KEYBOARD.T,
    KEYBOARD.Y,
    KEYBOARD.U,
    KEYBOARD.I,
    KEYBOARD.O,
    KEYBOARD.P,
    KEYBOARD.A,
    KEYBOARD.S,
    KEYBOARD.D,
    KEYBOARD.F,
    KEYBOARD.G,
    KEYBOARD.H,
    KEYBOARD.J,
    KEYBOARD.K,
    KEYBOARD.L,
    KEYBOARD.M,
    KEYBOARD.N,
    KEYBOARD.B,
    KEYBOARD.C,
    KEYBOARD.V,
    KEYBOARD.X,
    KEYBOARD.Z,
    KEYBOARD.Space,
    KEYBOARD.Comma,
    KEYBOARD.Period,
    KEYBOARD.Semicolon,
    KEYBOARD.Quote,
    KEYBOARD.BracketLeft,
    KEYBOARD.BracketRight,
    KEYBOARD.Backslash,
    KEYBOARD.Slash,
    KEYBOARD.Minus,
    KEYBOARD.Equal,
    KEYBOARD.Backquote,
]
